Add shellcheck to tests

diff --git a/bin/doco b/bin/doco
--- a/bin/doco
+++ b/bin/doco
@@ -22,20 +22,20 @@
 set -euo pipefail  # Strict mode
 mdsh-parse() {
 	local cmd=$1 lno=0 block_start lang block ln indent fence close_fence indent_remove
-	local open_fence='^( {0,3})(~~~+|```+) *([^`]*)$'
-	while let lno++; IFS= read -r ln; do
+	local open_fence=$'^( {0,3})(~~~+|```+) *([^`]*)$'
+	while ((lno++)); IFS= read -r ln; do
 		if [[ $ln =~ $open_fence ]]; then
 			indent=${BASH_REMATCH[1]} fence=${BASH_REMATCH[2]} lang=${BASH_REMATCH[3]} block=
 			block_start=$lno close_fence="^( {0,3})$fence+ *\$" indent_remove="^${indent// / ?}"
-			while let lno++; IFS= read -r ln && ! [[ $ln =~ $close_fence ]]; do
-				! [[ $ln =~ $indent_remove ]] || ln=${ln#$BASH_REMATCH}; block+=$ln$'\n'
+			while ((lno++)); IFS= read -r ln && ! [[ $ln =~ $close_fence ]]; do
+				! [[ $ln =~ $indent_remove ]] || ln=${ln#${BASH_REMATCH[0]}}; block+=$ln$'\n'
 			done
-			lang="${lang%"${lang##*[![:space:]]}"}"; $cmd fenced "$lang" "$block";
+			lang="${lang%"${lang##*[![:space:]]}"}"; "$cmd" fenced "$lang" "$block";
 		fi
 	done
 }
 mdsh-source() {
-	local MDSH_FOOTER= MDSH_SOURCE
+	local MDSH_FOOTER='' MDSH_SOURCE
 	if [[ ${1:--} != '-' ]]; then
 		MDSH_SOURCE="$1"
 		mdsh-parse __COMPILE__ <"$1"
@@ -47,32 +47,36 @@ mdsh-compile() (  # <-- force subshell to prevent escape of compile-time state
 	mdsh-source "$@"
 )
 __COMPILE__() {
-	[[ $1 == fenced && $fence == '```' && ! $indent ]] || return 0  # only unindented ``` code
+	[[ $1 == fenced && $fence == $'```' && ! $indent ]] || return 0  # only unindented ``` code
 	local lang="${2//[^_[:alnum:]]/_}"; # convert language to safe variable/function name
-	local tag_words=($2);  # check for command blocks first
+	local tag_words; mdsh-splitwords "$2" tag_words;  # check for command blocks first
 	if [[ ${tag_words[1]-} == '!'* ]]; then
 		set -- "$3" "$2" "$block_start"; eval "${2#*!}"; return
 	elif [[ ${tag_words[1]-} == '+'* ]]; then
-		printf "%s %q\n" "${2#"$tag_words"*+}" "$3"
+		printf '%s %q\n' "${2#"${tag_words[0]}"*+}" "$3"
 	elif [[ ${tag_words[1]-} == '|'* ]]; then
-		echo "${2#"$tag_words"*|} <<'\`\`\`'"; printf '%s```\n' "$3"; return
-	elif fn-exists mdsh-lang-$lang; then
-		mdsh-rewrite mdsh-lang-$lang "{" "} <<'\`\`\`'"; printf '%s```\n' "$3"
-	elif fn-exists mdsh-compile-$lang; then
-		mdsh-compile-$lang "$3" "$2" "$block_start"
+		echo "${2#"${tag_words[0]}"*|} <<'\`\`\`'"; printf $'%s```\n' "$3"; return
+	elif fn-exists "mdsh-lang-$lang"; then
+		mdsh-rewrite "mdsh-lang-$lang" "{" "} <<'\`\`\`'"; printf $'%s```\n' "$3"
+	elif fn-exists "mdsh-compile-$lang"; then
+		"mdsh-compile-$lang" "$3" "$2" "$block_start"
 	else
 		mdsh-misc "$2" "$3"
 	fi
 
-	if fn-exists mdsh-after-$lang; then
-		mdsh-rewrite mdsh-after-$lang
+	if fn-exists "mdsh-after-$lang"; then
+		mdsh-rewrite "mdsh-after-$lang"
 	fi
+}
+# split words in $1 into the array named by $2 (REPLY by default), without wildcard expansion
+mdsh-splitwords() {
+	set -f -- "$-" "$@";  eval "${3:-REPLY}"'=($2)'; [[ $1 == *f* ]] || set +f
 }
 # fn-exists: succeed if argument is a function
 fn-exists() { declare -F -- "$1"; } >/dev/null
 # Output body of func $1, optionally replacing the opening/closing { and } with $2 and $3
 mdsh-rewrite() {
-	declare -f $1 | sed -e '1d; 2s/^{ $/'"${2-"{"}"'/; $s/^}$/'"${3-"\}"}"'/'
+	local b='}' r; r="$(declare -f -- "$1")"; r=${r#*{ }; r=${r%\}*}; echo "${2-{}$r${3-$b}"
 }
 mdsh-misc()          { mdsh-data "$@"; }    # Treat unknown languages as data
 mdsh-compile-()      { :; }                 # Ignore language-less blocks
@@ -83,13 +87,13 @@ mdsh-compile-mdsh_main() { ! @is-main || eval "$1"; }
 mdsh-compile-shell() { printf '%s' "$1"; }  # Copy `shell` blocks to the output
 mdsh-compile-shell_main() { ! @is-main || printf '%s' "$1"; }
 mdsh-data() {
-	printf "mdsh_raw_${1//[^_[:alnum:]]/_}+=(%q)\n" "$2"
+	printf 'mdsh_raw_%s+=(%q)\n' "${1//[^_[:alnum:]]/_}" "$2"
 }
 mdsh-compile-shell_mdsh() {
-	indent= fence='```' __COMPILE__ fenced mdsh "$1"
+	indent='' fence=$'```' __COMPILE__ fenced mdsh "$1"
 }
 mdsh-compile-shell_mdsh_main() {
-	indent= fence='```' __COMPILE__ fenced "mdsh main" "$1"
+	indent='' fence=$'```' __COMPILE__ fenced "mdsh main" "$1"
 }
 # Main program: check for arguments and run markdown script
 mdsh-main() {
@@ -107,7 +111,7 @@ mdsh-main() {
 # MDSH_ZERO pointing to the original $0.
 
 function mdsh-interpret() {
-	printf -v cmd 'eval "$(%q --compile %q)"' "$0" "$1"
+	printf -v cmd $'eval "$(%q --compile %q)"' "$0" "$1"
 	MDSH_ZERO="$1" exec bash -c "$cmd" "" "${@:2}"
 }
 mdsh.--compile() {
@@ -119,7 +123,7 @@ mdsh.--compile() {
 
 mdsh.-c() { mdsh.--compile "$@"; }
 mdsh.--eval() {
-	(($# == 1)) && [[ $1 != - ]] ||
+	{ (($# == 1)) && [[ $1 != - ]]; } ||
 		mdsh-error "Usage: %s --eval FILENAME" "${0##*/}"
 	mdsh.--compile "$1"
 	echo $'__status=$? eval \'return $__status || exit $__status\' 2>/dev/null'
@@ -135,10 +139,11 @@ mdsh.--out() {
 
 mdsh.-o() { mdsh.--out "$@"; }
 # mdsh-error: printf args to stderr and exit w/EX_USAGE (code 64)
-mdsh-error() { printf "$1\n" "${@:2}" >&2; exit 64; }
+# shellcheck disable=SC2059  # argument is a printf format string
+mdsh-error() { printf "$1"'\n' "${@:2}" >&2; exit 64; }
 mdsh.--help() {
-	printf "Usage: %s [--out FILE] [ --compile | --eval ] markdownfile [args...]\n" "${0##*/}"
-	echo -e '
+	printf 'Usage: %s [--out FILE] [ --compile | --eval ] markdownfile [args...]\n' "${0##*/}"
+	echo $'
 Run and/or compile code blocks from markdownfile(s) to bash.
 Use a filename of `-` to run or compile from stdin.
 
@@ -185,7 +190,7 @@ mdsh-embed() {
 	}
 	contents=$'\n'$(<"$f")$'\n'
 	while [[ $contents == *$'\n'"$boundary"$'\n'* ]]; do
-		let ctr++; boundary="# --- EOF $base.$ctr ---"
+		((ctr++)); boundary="# --- EOF $base.$ctr ---"
 	done
 	printf $'{ if [[ $OSTYPE != cygwin && $OSTYPE != msys && -e /dev/fd/0 ]]; then source /dev/fd/0; else source <(cat); fi; } <<\'%s\'%s%s\n' "$boundary" "$contents" "$boundary"
 }
@@ -205,7 +210,7 @@ flatname() {
 }
 MDSH_CACHE=
 mdsh-use-cache() {
-	if !(($#)); then
+	if ! (($#)); then
 		set -- "${XDG_CACHE_HOME:-${HOME:+$HOME/.cache}}"
 		set -- "${1:+$1/mdsh}"
 	fi
@@ -223,6 +228,7 @@ mdsh-run() {
 # Compile `file` and source the result, passing along any positional arguments
 run-markdown() {
 	if [[ $BASH_VERSINFO == 3 ]]; then # bash 3 can't source from proc
+		# shellcheck disable=SC1091  # shellcheck shouldn't try to read stdin
 		source /dev/fd/0 "${@:2}" <<<"$(mdsh-source "${1--}")"
 	else source <(mdsh-source "${1--}") "${@:2}"
 	fi
@@ -242,12 +248,14 @@ mdsh-compile-jq_imports() { printf 'IMPORTS %q\n' "$1"$'\n'; }
 
 mdsh-compile-yml()  { y2j "$1"; mdsh-compile-json "$REPLY"; }
 mdsh-compile-yaml() { y2j "$1"; mdsh-compile-json "$REPLY"; }
+
+# shellcheck disable=SC2154  # jqmd_data is initialized by the runtime
 mdsh-compile-json() { mdsh-compile-jq "$jqmd_data($1)"; }
 
 const() {
 	case "${tag_words-}" in
-	yaml|yml) y2j "$block"; printf "DEFINE %q\n" "def $1: $REPLY ;"$'\n' ;;
-	json)     printf "DEFINE %q\n" "def $1: $block ;"$'\n' ;;
+	yaml|yml) y2j "$block"; printf 'DEFINE %q\n' "def $1: $REPLY ;"$'\n' ;;
+	json)     printf 'DEFINE %q\n' "def $1: $block ;"$'\n' ;;
 	*) mdsh-error "Invalid language for constant: '%s'" "${tag_words-}"
 	esac
 }
@@ -258,7 +266,7 @@ printf -v REPLY '%s\n' "${mdsh_raw_bash_runtime[@]}"; eval "$REPLY"
 printf -v REPLY 'mdsh:file-header() { ! @is-main || echo -n %q; }' "$REPLY"; eval "$REPLY"
 
 # Ensure (main) scripts process any leftover filters at end
-mdsh:file-footer() { ! @is-main || echo 'if [[ $0 == ${BASH_SOURCE-} ]] && HAVE_FILTERS; then RUN_JQ; fi'; }
+mdsh:file-footer() { ! @is-main || echo $'if [[ $0 == "${BASH_SOURCE[0]-}" ]] && HAVE_FILTERS; then RUN_JQ; fi'; }
 mdsh.--no-runtime() ( unset -f mdsh:file-header mdsh:file-footer; mdsh-main "$@"; )
 mdsh.--yaml() (
 	fn-exists "yaml2json:${1-}" || mdsh-error "No such yaml2json processor: ${1-}" || exit $?
@@ -270,34 +278,34 @@ mdsh.-R() { mdsh.--no-runtime "$@"; }
 mdsh.-y() { mdsh.--yaml "$@"; }
 #!/usr/bin/env bash
 
-realpath.location() { realpath.follow "$1"; realpath.absolute "$REPLY" ".."; }
-realpath.resolved() { realpath.follow "$1"; realpath.absolute "$REPLY"; }
-realpath.dirname()  { if [[ $1 =~ /+[^/]+/*$ ]]; then REPLY="${1%${BASH_REMATCH}}"; REPLY=${REPLY:-/}; else REPLY=.; fi }
-realpath.basename() { if [[ $1 =~ /*([^/]+)/*$ ]]; then REPLY="${BASH_REMATCH[1]}"; else REPLY=/; fi }
+realpath.location(){ realpath.follow "$1"; realpath.absolute "$REPLY" ".."; }
+realpath.resolved(){ realpath.follow "$1"; realpath.absolute "$REPLY"; }
+realpath.dirname() { if [[ $1 =~ /+[^/]+/*$ ]]; then REPLY="${1%${BASH_REMATCH[0]}}"; REPLY=${REPLY:-/}; else REPLY=.; fi }
+realpath.basename(){ if [[ $1 =~ /*([^/]+)/*$ ]]; then REPLY="${BASH_REMATCH[1]}"; else REPLY=/; fi }
 
 realpath.follow() {
 	local target
 	while [[ -L "$1" ]] && target=$(readlink -- "$1"); do
 		realpath.dirname "$1"
-		# Resolve symlink target relative to symlink's directory
+		# Resolve relative to symlink's directory
 		[[ $REPLY != . && $target != /* ]] && REPLY=$REPLY/$target || REPLY=$target
 		# Break out if we found a symlink loop
 		for target; do [[ $REPLY == "$target" ]] && break 2; done
-		# Add current result to the loop-detect list and tail-recurse
+		# Add to the loop-detect list and tail-recurse
 		set -- "$REPLY" "$@"
 	done
 	REPLY="$1"
 }
 
 realpath.absolute() {
-	REPLY=$PWD; local no_eg; shopt -q extglob || { no_eg=y; shopt -s extglob; }
+	REPLY=$PWD; local eg=extglob; ! shopt -q $eg || eg=; ${eg:+shopt -s $eg}
 	while (($#)); do case $1 in
 		/*) REPLY=/; set -- "${1##+(/)}" "${@:2}" ;;
 		*/*) set -- "${1%%/*}" "${1##${1%%/*}+(/)}" "${@:2}" ;;
 		''|.) shift ;;
 		..) realpath.dirname "$REPLY"; shift ;;
 		*) REPLY="${REPLY%/}/$1"; shift ;;
-	esac; done; ${no_eg:+shopt -u extglob}
+	esac; done; ${eg:+shopt -u $eg}
 }
 
 realpath.canonical() {
@@ -322,7 +330,7 @@ realpath.relative() {
 set -euo pipefail
 
 fn_exists() { declare -F -- "$1"; } >/dev/null
-fn_copy()   { REPLY="$(declare -f $1)"; eval "$2 ${REPLY#$1}"; }
+fn_copy()   { REPLY="$(declare -f "$1")"; eval "$2 ${REPLY#$1}"; }
 findup()    { walkup "${1:-$PWD}" reply_if_exists "${@:2}"; }
 
 reply_if_exists() {
@@ -361,6 +369,7 @@ _loco_do() {
 }
 
 _loco_findproject() {
+    # shellcheck disable=SC2015  # plain var assign can't be false
     findup "$LOCO_PWD" "${LOCO_FILE[@]}" && LOCO_PROJECT=$REPLY ||
         loco_error "Can't find $LOCO_FILE here";
 }
@@ -374,6 +383,7 @@ _loco_user_config() { source "$1"; }
 
 # Find our configuration, exposing relevant paths and defaults
 
+# shellcheck disable=SC2034  # some vars are only used by extending scripts
 _loco_config() {
     LOCO_ARGS=("$@")
     loco_preconfig "$@"
@@ -394,7 +404,7 @@ _loco_config() {
 
 _loco_main() {
     loco_config "$@"
-    fn_exists $LOCO_NAME || eval "$LOCO_NAME() { loco_do \"\$@\"; }"
+    fn_exists "$LOCO_NAME" || eval "$LOCO_NAME() { loco_do \"\$@\"; }"
     ${LOCO_PROJECT:+:} loco_findproject "$@"
     ${LOCO_ROOT:+:}    loco_findroot "$@"
     loco_loadproject "$LOCO_PROJECT"
@@ -407,12 +417,12 @@ for f in $(compgen -A function _loco_); do
 done
 
 # Clear all LOCO_*  variables before beginning
-for lv in ${!LOCO_@}; do unset $lv; done
+for lv in ${!LOCO_@}; do unset "$lv"; done
 
 LOCO_SCRIPT=$0
 loco_preconfig() {
     export COMPOSE_PROJECT_NAME=
-    LOCO_FILE=("*[-.]doco.md" ".doco" "docker-compose.yml")
+    LOCO_FILE=("?*[-.]doco.md" ".doco" "docker-compose.yml")
     LOCO_NAME=doco
     LOCO_USER_CONFIG=$HOME/.config/doco
     LOCO_SITE_CONFIG=/etc/doco/config
@@ -424,8 +434,8 @@ loco_loadproject() {
     local json=$COMPOSE_FILE; DOCO_CONFIG=
 
     realpath.basename "$1"; case "$REPLY" in
-    *[-.]doco.md)
-        check_multi doco.md *[-.]doco.md
+    ?*[-.]doco.md)
+        check_multi doco.md '?*[-.]doco.md'
         include "$1" "$LOCO_ROOT/.doco-cache.sh"
         ;;
     *)
@@ -454,6 +464,7 @@ add_override() { while (($#)); do [[ ! -f "$1" ]] || COMPOSE_FILE+=$'\n'"$1"; sh
 
 # Abort if more than one given filename exists
 check_multi() {
+   # shellcheck disable=SC2012,SC2068  # we're using wc and glob expansion is intentional
    (("$(ls ${@:2} 2>/dev/null | wc -l)" < 2)) || loco_error "Multiple $1 files in $LOCO_ROOT"
 }
 ALIAS() {
@@ -471,25 +482,26 @@ export-env() {
     while IFS= read -r; do
         REPLY="${REPLY#"${REPLY%%[![:space:]]*}"}"  # trim leading whitespace
         REPLY="${REPLY%"${REPLY##*[![:space:]]}"}"  # trim trailing whitespace
-        [[ ! "$REPLY" || "$REPLY" == '#'* ]] || export "$REPLY"
+        [[ ! "$REPLY" || "$REPLY" == '#'* ]] || export "${REPLY?}"
     done <"$1"
 }
 export-source() {
     local before="" after=""
     before="$(compgen -v)"; source "$@"; after="$(compgen -v)"
     after="$(echo "$after" | grep -vxF -f <(echo "$before"))" || true
-    [[ -z "$after" ]] || export $after
+    [[ -z "$after" ]] || eval "export $after"
 }
 alias-exists() { fn-exists "doco-alias-$1"; }
 DOCO_OPTS=()
 compose() { docker-compose ${DOCO_OPTS[@]+"${DOCO_OPTS[@]}"} "$@"; }
-find-services() { REPLY=($(RUN_JQ -r "services_matching(${1-true}) | .key" "$DOCO_CONFIG")); }
+find-services() { REPLY=$(RUN_JQ -r "services_matching(${1-true}) | .key" "$DOCO_CONFIG") && IFS=$'\n' mdsh-splitwords "$REPLY"; }
 foreach-service() {
     for REPLY in ${DOCO_SERVICES[@]+"${DOCO_SERVICES[@]}"}; do
         local DOCO_SERVICES=("$REPLY"); "$@"
     done
 }
 get-alias() { REPLY=(); ! alias-exists "$1" || "doco-alias-$1"; }
+# shellcheck disable=SC2120  # shellcheck doesn't understand optional arguments
 have-services() { eval "((${#DOCO_SERVICES[@]} ${1-}))"; }
 include() {
     realpath.absolute "$1"
@@ -505,7 +517,7 @@ project-name() {
     REPLY=${COMPOSE_PROJECT_NAME-}
     [[ $REPLY ]] || realpath.basename "$LOCO_ROOT"   # default to directory name
     REPLY=${REPLY//[^[:alnum:]]/}; REPLY=${REPLY,,}  # lowercase and remove non-alphanumerics
-    ! (($#)) || REPLY+="_${1}_${2-1}"                # container name
+    ! (($#)) || REPLY=$REPLY"_${1}_${2-1}"           # container name
 }
 require-services() {
     case "$1${#DOCO_SERVICES[@]}" in
@@ -567,6 +579,7 @@ __compose_one() {
 }
 docker-compose-options() {
     while (($#)); do
+        # shellcheck disable=SC2089  # shellcheck hates metaprogramming
         printf -v REPLY 'doco.%s() { doco-opt %s doco "$@"; }' "$1" "$1"; eval "$REPLY"; shift
     done
 }
@@ -598,24 +611,25 @@ doco.--where() {
     elif ! ((${#REPLY[@]})); then
         echo "No matching services" >&2; return 1
     else
-        printf "%s\n" "${REPLY[@]}"   # list matching services
+        printf '%s\n' "${REPLY[@]}"   # list matching services
     fi
 }
 # Execute the rest of the command line with specified service(s)
 doco.--with() { with-service "$1" doco "${@:2}"; }
 doco.--with-default() {
-    if have-services; then doco "${@:2}"; else with-alias "$1" doco "${@:2}"; fi
+    if have-services ''; then doco "${@:2}"; else with-alias "$1" doco "${@:2}"; fi
 }
 doco.--require-services() {
     [[ ${1:0:1} == [-+1.] ]] || loco_error "--require-services argument must begin with ., -, +, or 1"
-    require-services $1 "$2" && doco "${@:2}";
+    # shellcheck disable=SC2090  # bash 4.3 needs this syntax because "${x[@]:0}" doesn't play nice w/-u
+    mdsh-splitwords "$1" && require-services ${REPLY[@]+"${REPLY[@]}"} "$2" && doco "${@:2}";
 }
 doco.cmd() { doco --with-default cmd-default --require-services "$@"; }
 doco.cp() {
-    local opts= seen=
+    local opts=() seen=''
     while (($#)); do
         case "$1" in
-        -a|--archive|-L|--follow-link) opts+=" $1" ;;
+        -a|--archive|-L|--follow-link) opts+=("$1") ;;
         --help|-h) docker help cp || true; return ;;
         -*) loco_error "Unrecognized option $1; see 'docker help cp'" ;;
         *) break ;;
@@ -632,20 +646,21 @@ doco.cp() {
             elif ((${#DOCO_SERVICES[@]} == 1)); then
                 project-name "$DOCO_SERVICES"; set -- "$REPLY$1" "${@:2}"
             else
-                doco --with-default shell-default --require-services 1 cp $opts "$@"; return $?
+                doco --with-default shell-default --require-services 1 cp ${opts[@]+"${opts[@]}"} "$@"; return $?
             fi
         elif [[ $1 != /* && $1 != - ]]; then
             # make paths relative to original run directory
             set -- "$LOCO_PWD/$1" "${@:2}";
         fi
-        printf -v opts "%s %q" "$opts" "$1"; shift
+        opts+=("$1"); shift
     done
     [[ "$seen" ]] || loco_error "cp: either source or destination must contain a :"
-    docker cp $opts
+    docker cp ${opts[@]+"${opts[@]}"}
 }
 doco.foreach() { foreach-service doco "$@"; }
 doco.jq() { RUN_JQ "$@" <"$DOCO_CONFIG"; }
 doco.sh() { doco cmd 1 exec bash "$@"; }
 DEFINE "${mdsh_raw_jq_api[*]}"
-mdsh-error() { printf -v REPLY "$1\n" "${@:2}"; loco_error "$REPLY"; }
+# shellcheck disable=SC2059  # argument is a printf format string
+mdsh-error() { printf -v REPLY "$1"'\n' "${@:2}"; loco_error "$REPLY"; }
 if [[ $0 == "${BASH_SOURCE-}" ]]; then loco_main "$@"; fi
