Switch to c3-mro for method dispatching

diff --git a/bin/doco b/bin/doco
--- a/bin/doco
+++ b/bin/doco
@@ -458,6 +458,46 @@ done
 for lv in ${!LOCO_@}; do unset "$lv"; done
 
 LOCO_SCRIPT=$0
+declare -gA c3_mro c3_cache=() c3_seen=()
+c3::call(){ ${c3_cache["$2$1"]-c3::invoke "$1" "$2"} "${@:3}";}
+c3::super(){ : "${1#*<$2>}"; ${c3_cache["$3$_"]-c3::invoke "$_" "$3"} "${@:4}";}
+c3::invoke(){ REPLY= c3::find-method "$1" "$2"; ${c3_cache["$2$1"]-c3::unknown-method "$1" "$2"} "${@:3}";}
+c3::find-method(){
+	REPLY=("${c3_cache["$2$1"]-}");${REPLY:+return};REPLY=${1%%>*};REPLY=${REPLY#<}::$2
+	c3_seen["$REPLY"]=
+	if c3::exists "$REPLY"||{ [[ ${1#*>} ]]&& c3::find-method "${1#*>}" "$2";}
+	then c3_cache["$2$1"]=$REPLY; else REPLY=; false; fi
+}
+c3::unknown-method(){ echo -n "Unknown method: $2 in $*; at ";caller 3;exit 70;} >&2
+c3::resolve(){
+	local -n mro=c3_mro["$1"]
+	case $# in 1|2) mro="<$1>${2:+${c3_mro[$2]=<$2>}}";; 0) return;;
+	*) printf -v mro '<%s>' "$@"; c3::mixin mro "${@:2}"
+	esac
+}
+c3::mixin(){
+	local REPLY t m=(); for t in "${@:2}"; do m+=("${c3_mro[$t]=<$t>}"); done
+	c3::merge ${m[@]+"${m[@]}"} "${!1}" && printf -v "$1" %s "$REPLY"
+}
+c3::merge(){
+	if (($#==1)); then REPLY=("$1"); return; fi
+	local list head f=$-; set -f; REPLY=("")
+	while (($#)); do
+		for list; do
+			[[ $list ]] || continue; head="${list%%>*}>"
+			if [[ "$*" == "${*/">$head"*/}" ]]; then
+				REPLY[0]+=$head; set -- ${*//"$head"/}; continue 2
+			fi
+		done
+		break # error, can't merge
+	done
+	[[ $f == *f* ]] || set +f
+	((!$#))  # fail if unmerged args
+}
+c3::defun(){ [[ $1 != *::* ]]||c3::exists "$1"||${c3_seen["$1"]+c3::methods-changed};eval "$1(){ ${2:-:}"$'\n}';}
+c3::methods-changed(){ c3_cache=(); c3_seen=();}
+c3::undef(){ local m; for m; do c3::exists "$m" && unset -f "$m" && ${c3_seen["$m"]+c3::methods-changed} ||:; done;}
+c3::exists(){ declare -pF "$1" &>/dev/null;}
 project-is-finalized() { [[ ${DOCO_CONFIG-} ]]; }
 loco_preconfig() {
     set -- "${BASH_VERSINFO[@]}"
@@ -585,13 +625,15 @@ __ev.list(){ REPLY=("${!bashup_ev[@]}");[[ $1 ]]||return 0;s=$1;set -- "${REPLY[
 }
 is-target-name() { [[ $1 && $1 != *[^-._A-Za-z0-9]* ]]; }
 
+c3::resolve doco-target
+c3::resolve @current-target doco-target
 target() {
-	local TARGET_NAME="$1" __mro__=(doco-target)
+	local TARGET_NAME="$1" __class__=doco-target
 	if is-target-name "$1"; then
 		local t=${1//_/_5f}; t=${t//./_2e}; t=${t//-/_2d}
 		local TARGET_VAR=__doco_target_$t
 	elif [[ $1 == @current ]]; then
-		local TARGET_VAR=DOCO_SERVICES __mro__=(@current-target doco-target)
+		local TARGET_VAR=DOCO_SERVICES __class__=@current-target
 	else fail "Group or service name '$1' contains invalid characters" || return
 	fi
 	local -n TARGET="$TARGET_VAR"
@@ -600,13 +642,7 @@ target() {
 }
 
 fail() { echo "$1">&2; return "${2-64}"; }
-this() {
-	if (($#)); then
-		local m; for m in "${__mro__[@]}"; do if fn-exists "$m::$1"; then break; fi; done
-		"$m::$@"
-	fi
-}
-
+this() { ${1:+c3::call "${c3_mro["$__class__"]}" "$@"};}
 array-exists() { declare -p "$1" >/dev/null 2>&1; }
 
 doco-target::exists() { [[ ${TARGET+_} ]] || array-exists "$TARGET_VAR"; }
