Overhaul cmd/option parsing & compose integration

diff --git a/bin/doco b/bin/doco
--- a/bin/doco
+++ b/bin/doco
@@ -674,71 +674,165 @@ get-alias() { target "$1" get || true; }
 set-alias() { target "$1" set "$@"; }
 with-alias() { target "$1" call "${@:2}"; }
 with-service() { mdsh-splitwords "$1"; with-targets @current "${REPLY[@]}" -- "${@:2}"; }
-DOCO_OPTS=()
-compose() { docker-compose ${DOCO_OPTS[@]+"${DOCO_OPTS[@]}"} "$@"; }
-loco_exec() {
-    if is-target-name "$1" && target "$1" exists; then
-        with-targets @current "$1" -- ${2+doco "${@:2}"};
-    else
-        compose "$@" ${DOCO_SERVICES[@]+"${DOCO_SERVICES[@]}"};
-    fi
+# doco opt OPTION CMD...  --> run CMD with OPTION added to project options
+doco-opt() { local DOCO_OPTS=("${DOCO_OPTS[@]}" "$1"); "${@:2}"; }
+
+# compose SUBCOMMAND... --> docker-compose DOCO_OPTS SUBCOMMAND...
+compose() { docker-compose "${DOCO_OPTS[@]}" "$@"; }
+
+# Global docker-compose flags
+doco.--verbose()   { doco-opt --verbose   doco "$@"; }
+doco.--no-ansi()   { doco-opt --no-ansi   doco "$@"; }
+doco.--tls()       { doco-opt --tls       doco "$@"; }
+doco.--tlsverify() { doco-opt --tlsverify doco "$@"; }
+
+doco.--skip-hostname-check() { doco-opt --skip-hostname-check doco "$@"; }
+
+# Options that take arguments
+function doco.-H=()          { doco-opt -H="$1"          doco "${@:2}"; }
+function doco.--host=()      { doco-opt --host="$1"      doco "${@:2}"; }
+function doco.--tlscacert=() { doco-opt --tlscacert="$1" doco "${@:2}"; }
+function doco.--tlscert=()   { doco-opt --tlscert="$1"   doco "${@:2}"; }
+function doco.--tlskey=()    { doco-opt --tlskey="$1"    doco "${@:2}"; }
+
+# Informational options
+doco.-h()        { docker-compose -h        "$@"; }
+doco.-v()        { docker-compose -v        "$@"; }
+doco.--help()    { docker-compose --help    "$@"; }
+doco.--version() { docker-compose --version "$@"; }
+
+# Project options can't be set on the command line
+
+function doco.--project-name=() {
+	loco_error "You must use COMPOSE_PROJECT_NAME to set the project name."
+}
+function doco.--file=() {
+	loco_error "doco does not support -f and --file."
+}
+function doco.--project-directory=() {
+	loco_error "doco: --project-directory cannot be overridden"
+}
+function doco.-f=() { doco --file "$@"; }
+function doco.-p=() { doco --project-name "$@"; }
+
+# All supported docker-compose subcommands should be placed here
+doco.build()   { compose-targeted   build   "$@"; }
+doco.bundle()  { compose-untargeted bundle  "$@"; }
+doco.config()  { compose-untargeted config  "$@"; }
+doco.create()  { compose-targeted   up --no-start "$@"; }
+doco.down()    { compose-untargeted down    "$@"; }
+doco.events()  { compose-targeted   events  "$@"; }
+doco.exec()    { compose-singular   exec \
+	'-e|--env|-u|--user|--index' "$@"; }
+doco.help()    { docker-compose     help    "$@"; }
+doco.images()  { compose-targeted   images  "$@"; }
+doco.kill()    { compose-targeted   kill    "$@"; }
+doco.logs()    { compose-targeted   logs    "$@"; }
+doco.pause()   { compose-targeted   pause   "$@"; }
+doco.port()    { compose-singular   port \
+	'--protocol|--index' "$@"; }
+doco.ps()      { compose-targeted   ps      "$@"; }
+doco.pull()    { compose-targeted   pull    "$@"; }
+doco.push()    { compose-targeted   push    "$@"; }
+doco.restart() { compose-targeted   restart "$@"; }
+doco.rm()      { compose-targeted   rm      "$@"; }
+doco.run()     { compose-singular   run \
+	'-p|--publish|-v|--volume|-w|--workdir|-e|--env|-u|--user|--name|--entrypoint' "$@"; }
+doco.scale()   { compose-untargeted scale   "$@"; }
+doco.start()   { compose-targeted   start   "$@"; }
+doco.stop()    { compose-targeted   stop    "$@"; }
+doco.top()     { compose-targeted   top     "$@"; }
+doco.unpause() { compose-targeted   unpause "$@"; }
+doco.up()      { compose-targeted   up      "$@"; }
+doco.version() { docker-compose     version "$@"; }
+
+# Commands that accept services
+compose-targeted() {
+	any-target @current || true  # ok if none are set
+	compose "$@" "${REPLY[@]}"
 }
 # Commands that don't accept a list of services
-for cmd in bundle config down help scale version; do
-    eval "doco.$cmd() { compose $cmd \"\$@\"; }"
-done
-doco.exec() { __compose_one exec '-e|--env|-u|--user|--index' "$@"; }
-doco.run()  { __compose_one run  '-p|--publish|-v|--volume|-w|--workdir|-e|--env|-u|--user|--name|--entrypoint' "$@"; }
-doco.port() { __compose_one port '--protocol|--index' "$@"; }
+compose-untargeted() {
+	target @current has-count ==0 || fail "$1 cannot target specific services" || return
+	compose "$@";
+}
+compose-singular() {
+	local svc cmd=$1 opts=^$2\$ argv=("$1"); shift
 
-__compose_one() {
-    local svc opts=^$2\$ argv=("$1"); shift
-
-    # Parse the command line, skipping options' argument values
-    while shift && (($#)) && [[ $1 == -* ]]; do
-        # Treat '--' as end of options
-        if [[ $1 == -- ]]; then shift; break; fi
-        argv+=("$1"); if [[ $1 =~ $opts ]]; then shift; argv+=("$1"); fi
+	# Parse the command line, skipping options' argument values
+	while shift && (($#)) && [[ $1 == -* ]]; do
+		# Treat '--' as end of options
+		if [[ $1 == -- ]]; then shift; break; fi
+		argv+=("$1"); if [[ $1 =~ $opts ]]; then shift; argv+=("$1"); fi
     done
 
-    if have-services; then
-        for svc in "${DOCO_SERVICES[@]}"; do compose "${argv[@]}" "$svc" "$@"; done
-    else
-        # XXX should check that $1 is a valid service
-        compose "${argv[@]}" "$@"
-    fi
-}
-docker-compose-options() {
-    while (($#)); do
-        # shellcheck disable=SC2089  # shellcheck hates metaprogramming
-        printf -v REPLY 'doco.%s() { doco-opt %s doco "$@"; }' "$1" "$1"; eval "$REPLY"; shift
-    done
+	if ! any-target @current || ! ((${#REPLY[@]})) ; then
+		# no current or default target, check command line for one
+		if ((! $#)) || ! target "$1" get; then
+			fail "No service/group specified for $cmd" || return
+		else
+			shift  # remove the explicit target from the tail
+		fi
+	fi
+	if ((${#REPLY[@]} != 1)); then
+		with-targets "${REPLY[@]}" -- require-services 1 "$cmd"
+	else
+		compose "${argv[@]}" "${REPLY[@]}" "$@"
+	fi
 }
 
-docker-compose-optargs() {
-    while (($#)); do
-        eval "doco.$1() { doco-opt $1 doco-opt \"\$1\" doco \"\${@:2}\"; }"; shift
-    done
+loco_do() {
+	[[ "${1-}" ]] || loco_usage   # No non-empty command given, exit w/usage
+	case $1 in
+		--*=*)    doco-optarg  "$@" ;;  # --[option]=value
+		--*)      doco-option  "$@" ;;  # --[option]
+		-[^=]=*)  doco-optarg  "$@" ;;  # -a=bcd
+		-[^=]?*)  doco-options "$@" ;;  # -abcd
+		-?)       doco-option  "$@" ;;  # -x
+		*)        doco-other   "$@" ;;  # commands, services, and groups
+	esac
 }
-doco-opt() { local DOCO_OPTS=(${DOCO_OPTS[@]+"${DOCO_OPTS[@]}"} "$1"); "${@:2}"; }
-docker-compose-options --verbose --no-ansi --tls --tlsverify --skip-hostname-check
-docker-compose-optargs -H --host --tlscacert --tlscert --tlskey
-docker-compose-immediate() {
-    while (($#)); do eval "doco.$1() { docker-compose $1 \"\$@\"; }"; shift; done
+doco-options() {
+	if fn-exists "doco.${1:0:2}="; then
+		"doco.${1:0:2}=" "${1:2}" "${@:2}"  # -a= bcd ...
+	elif fn-exists "doco.${1:0:2}"; then
+		"doco.${1:0:2}" "-${1:2}" "${@:2}"  # -a -bcd ...
+	else doco-other "$@"   # maybe -abcd is a command, group, or service?
+	fi
 }
-docker-compose-immediate -h --help -v --version
-doco.-p() { loco_error "You must use COMPOSE_PROJECT_NAME to set the project name."; }
-doco.-f() { loco_error "doco does not support -f and --file."; }
-doco.--file() { doco -f "$@"; }
-doco.--project-name() { doco -p "$@"; }
-doco.--project-directory() { loco_error "doco: --project-directory cannot be overridden"; }
+
+doco-option() {
+	if fn-exists "doco.$1"; then "doco.$@"
+	elif fn-exists "doco.$1="; then
+		if (($#>1)); then "doco.$1=" "${@:2}"
+		else fail "$1 requires an argument"
+		fi
+	else doco-other "$@"   # maybe --longopt is a group or service?
+	fi
+}
+
+doco-optarg() {
+	if fn-exists "doco.${1%%=*}="; then
+		"doco.${1%%=*}=" "${1#*=}" "${@:2}"
+	elif fn-exists "doco.${1%%=*}"; then
+		fail "${1%%=*} does not accept values"
+	else doco-other "$@"   # maybe it's a command/group/service?
+	fi
+}
+doco-other() {
+	if fn-exists "doco.$1"; then "doco.$@"
+	elif is-target-name "$1" && target "$1" exists; then
+		with-targets @current "$1" -- ${2+doco "${@:2}"}
+	else fail "'$1' is not a recognized option, command, service, or group"
+	fi
+}
 # Execute the rest of the command line with NO specified service(s)
 doco.--()   { with-targets -- doco "$@"; }
 doco.--all() { doco --where true "$@"; }
-doco.--where() {
+function doco.--where=() {
     find-services "${@:1}"
     if (($#>1)); then
-        with-targets "${REPLY[@]}" -- doco "${@:2}"   # run command on matching services
+        with-targets @current "${REPLY[@]}" -- doco "${@:2}"   # run command on matching services
     elif ! ((${#REPLY[@]})); then
         echo "No matching services" >&2; return 1
     else
@@ -746,15 +840,16 @@ doco.--where() {
     fi
 }
 # Execute the rest of the command line with specified service(s)
-doco.--with() { mdsh-splitwords "$1"; with-targets @current "${REPLY[@]}" -- doco "${@:2}"; }
-doco.--with-default() {
+function doco.--with=() {
+	mdsh-splitwords "$1"; with-targets @current "${REPLY[@]}" -- doco "${@:2}"
+}
+function doco.--with-default=() {
     if target @current has-count || ! target "$1" exists; then doco "${@:2}"
     else with-targets "$1" -- doco "${@:2}"; fi
 }
-doco.--require-services() {
+function doco.--require-services=() {
     [[ ${1:0:1} == [-+1.] ]] || loco_error "--require-services argument must begin with ., -, +, or 1"
-    # shellcheck disable=SC2090  # bash 4.3 needs this syntax because "${x[@]:0}" doesn't play nice w/-u
-    mdsh-splitwords "$1" && require-services ${REPLY[@]+"${REPLY[@]}"} "$2" && doco "${@:2}";
+    mdsh-splitwords "$1" && require-services "${REPLY[@]}" "${2-}" && doco "${@:2}";
 }
 doco.cmd() { doco --with-default cmd-default --require-services "$@"; }
 doco.cp() {
@@ -776,9 +871,10 @@ doco.cp() {
             if [[ "${1%%:*}" ]]; then
                 project-name "${1%%:*}"; set -- "$REPLY:${1#*:}" "${@:2}"
             elif have-services '==1'; then
-                project-name "$DOCO_SERVICES"; set -- "$REPLY$1" "${@:2}"
+                project-name "${DOCO_SERVICES[0]}"; set -- "$REPLY$1" "${@:2}"
             else
-                doco --with-default shell-default --require-services 1 cp ${opts[@]+"${opts[@]}"} "$@"; return $?
+                doco --with-default=shell-default --require-services=1 cp "${opts[@]}" "$@"
+                return
             fi
         elif [[ $1 != /* && $1 != - ]]; then
             # make paths relative to original run directory
